# Behavior Configuration for Hexapod Robot
# Defines gait patterns, navigation parameters, and autonomy settings

# Gait Configuration
gaits:
  # Tripod gait (default, fastest)
  tripod:
    name: "tripod"
    speed: 1.0             # Relative speed multiplier
    step_height: 30.0      # mm
    step_length: 60.0      # mm
    duty_factor: 0.5       # Fraction of cycle with foot on ground
    cycle_time: 1.0        # seconds per complete gait cycle
    stability: 0.8         # Stability rating (0-1)
    energy_cost: 1.0       # Relative energy consumption

    # Leg groupings (legs that move together)
    groups:
      - [0, 2, 4]          # Group 1: Front-right, Rear-right, Middle-left
      - [1, 3, 5]          # Group 2: Middle-right, Rear-left, Front-left

  # Wave gait (slower, more stable)
  wave:
    name: "wave"
    speed: 0.5
    step_height: 25.0
    step_length: 40.0
    duty_factor: 0.83
    cycle_time: 2.0
    stability: 0.95
    energy_cost: 0.8

    # Sequential leg movement pattern
    sequence: [0, 5, 1, 4, 2, 3]

  # Ripple gait (medium speed/stability)
  ripple:
    name: "ripple"
    speed: 0.7
    step_height: 28.0
    step_length: 50.0
    duty_factor: 0.67
    cycle_time: 1.5
    stability: 0.85
    energy_cost: 0.9

    groups:
      - [0, 3]             # Group 1
      - [1, 4]             # Group 2
      - [2, 5]             # Group 3

# Gait Selection Parameters
gait_selection:
  default: "tripod"

  # Auto-select gait based on conditions
  auto_select:
    enabled: true

    # Speed-based selection
    speed_thresholds:
      - speed_max: 0.3     # m/s
        gait: "wave"
      - speed_max: 0.6
        gait: "ripple"
      - speed_max: 1.0
        gait: "tripod"

    # Terrain-based selection
    terrain:
      flat: "tripod"
      rough: "wave"
      slope: "ripple"
      obstacle: "wave"

    # Battery-based selection (switch to energy-efficient gait when low)
    battery_threshold: 20.0  # percent

# Navigation Parameters
navigation:
  # Path planning
  path_planning:
    algorithm: "A_star"    # Options: A_star, RRT, DWA
    grid_resolution: 0.1   # meters
    max_planning_time: 2.0 # seconds
    replan_interval: 5.0   # seconds
    goal_tolerance: 0.2    # meters

  # Obstacle avoidance
  obstacle_avoidance:
    enabled: true
    safety_margin: 0.3     # meters
    detection_range: 2.0   # meters
    reaction_time: 0.5     # seconds

    # Obstacle detection thresholds
    lidar_threshold: 0.5   # meters
    ultrasonic_threshold: 0.3  # meters
    vision_threshold: 0.6  # meters

  # Localization
  localization:
    method: "EKF"          # Extended Kalman Filter
    gps_weight: 0.7        # GPS vs dead-reckoning weight
    update_rate: 10        # Hz

    # Dead reckoning parameters
    odometry:
      enabled: true
      drift_compensation: true

  # Speed limits
  speed:
    max_linear: 0.8        # m/s
    max_angular: 45.0      # degrees/s
    default_linear: 0.4    # m/s
    emergency_stop_decel: 2.0  # m/s^2

# Autonomy & Decision Making
autonomy:
  # Operational modes
  modes:
    - name: "autonomous"
      description: "Fully autonomous operation"
      operator_approval_required: false

    - name: "semi_autonomous"
      description: "Autonomous with operator oversight"
      operator_approval_required: true

    - name: "remote_control"
      description: "Manual operator control"
      operator_approval_required: false

    - name: "emergency_stop"
      description: "Emergency stop mode"
      operator_approval_required: false

  default_mode: "semi_autonomous"

  # Risk assessment thresholds (0-100 scale)
  risk_thresholds:
    # Critical risks - always require operator approval
    cliff_detection: 95
    steep_slope: 90
    unstable_terrain: 85
    collision_imminent: 95
    battery_critical: 90   # <5% battery

    # High risks - require approval in semi-autonomous mode
    unknown_obstacle: 70
    GPS_signal_lost: 75
    large_obstacle: 65
    steep_incline: 70
    communication_loss: 80

    # Medium risks - autonomous decision with logging
    small_obstacle: 40
    path_deviation: 50
    mild_incline: 35
    sensor_degraded: 55

    # Low risks - autonomous handling
    terrain_variation: 20
    minor_course_correction: 15

  # Decision timeout parameters
  decision_timeout:
    operator_response_timeout: 30.0  # seconds
    default_action_on_timeout: "stop"  # Options: stop, continue, fallback

  # Emergency protocols
  emergency:
    auto_switch_remote_control: true
    triggers:
      - "battery_critical"
      - "collision_imminent"
      - "communication_loss_extended"
      - "sensor_failure_critical"
      - "unstable_orientation"

    # Failsafe actions
    failsafe:
      battery_critical: "stop_and_signal"
      sensor_failure: "switch_to_manual"
      communication_loss: "hold_position"
      unstable_orientation: "crouch_and_stabilize"

# Energy Management
energy:
  # Battery parameters
  battery:
    capacity: 5000.0       # mAh
    voltage_nominal: 11.1  # V (3S LiPo)
    voltage_min: 9.0       # V
    voltage_max: 12.6      # V

  # Energy-aware behavior
  optimization:
    enabled: true
    low_battery_threshold: 30.0   # percent
    critical_battery_threshold: 10.0  # percent

    # Low battery actions
    low_battery_actions:
      - "switch_to_wave_gait"
      - "reduce_max_speed"
      - "reduce_telemetry_frequency"
      - "disable_non_critical_sensors"

    # Critical battery actions
    critical_battery_actions:
      - "return_to_base"
      - "find_charging_station"
      - "signal_operator"
      - "minimal_operation_mode"

  # Power consumption monitoring
  monitoring:
    update_rate: 1.0       # Hz
    log_enabled: true
    alert_on_anomaly: true

# Vision & Perception
perception:
  # Object detection (YOLOv8)
  object_detection:
    enabled: true
    confidence_threshold: 0.5
    nms_threshold: 0.4
    classes_of_interest:
      - "person"
      - "car"
      - "obstacle"
      - "animal"
      - "tree"
      - "rock"

  # Terrain classification
  terrain_classification:
    enabled: true
    update_rate: 2.0       # Hz
    classes:
      - "flat_ground"
      - "rough_terrain"
      - "grass"
      - "gravel"
      - "sand"
      - "rocks"

  # Depth estimation
  depth_estimation:
    enabled: false         # Enable if using monocular depth
    range_max: 10.0        # meters

# Telemetry & Logging
telemetry:
  # Data collection
  collection:
    enabled: true
    local_storage: true
    remote_sync: true

  # Update rates (Hz)
  update_rates:
    position: 1.0
    orientation: 10.0
    servo_state: 5.0
    sensor_data: 2.0
    battery_status: 0.2
    system_health: 0.1

  # LoRaWAN transmission
  lorawan:
    enabled: true
    base_interval: 60.0    # seconds (when idle)
    active_interval: 30.0  # seconds (when moving)
    critical_immediate: true  # Send critical events immediately

    # Adaptive transmission based on battery
    adaptive:
      enabled: true
      low_battery_interval: 120.0   # seconds
      critical_battery_interval: 300.0  # seconds

  # Data prioritization (1=highest, 5=lowest)
  priority:
    emergency_events: 1
    operator_requests: 1
    critical_battery: 1
    collision_warning: 1
    position_updates: 2
    sensor_data: 3
    system_logs: 4
    diagnostic_data: 5

# Calibration & Tuning
calibration:
  # IMU calibration
  imu:
    auto_calibrate_on_startup: true
    calibration_duration: 10.0  # seconds

  # Servo calibration
  servos:
    auto_center_on_startup: true
    neutral_position_test: true

  # Gait tuning
  gait_tuning:
    learning_enabled: false  # Future: ML-based gait optimization
    terrain_adaptation: true
